# Generated by Django 5.1 on 2024-08-18 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('id_aliquotas', models.AutoField(primary_key=True, serialize=False)),
                ('deducao_imposto', models.IntegerField()),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estadual',
            fields=[
                ('ie', models.AutoField(primary_key=True, serialize=False)),
                ('login_estadual', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_estadual', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_estadual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('login_federal', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_federal', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_federal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FonteReceita',
            fields=[
                ('id_fonte_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('ccm', models.AutoField(primary_key=True, serialize=False)),
                ('login_municipal', models.CharField(blank=True, max_length=100, null=True)),
                ('senha_municipal', models.CharField(blank=True, max_length=100, null=True)),
                ('certificado_digital_municipal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id_data_vencimento', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('periodo_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('responsaveis', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=100)),
                ('ie_estadual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadual')),
                ('cnpj_federal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federal')),
                ('ccm_municipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.municipal')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaFonteReceita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_fonte_receita_fonte_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fontereceita')),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id_transacoes', models.AutoField(primary_key=True, serialize=False)),
                ('transacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tributo',
            fields=[
                ('id_tributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('id_fonte_receita_fonte_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fontereceita')),
                ('id_data_vencimento_vencimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTributo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_tributo_tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tributo')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioAliquotas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aliquotas_criterios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.criterios')),
                ('id_tributo_tributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tributo')),
            ],
        ),
    ]
