# Generated by Django 5.1 on 2024-08-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_criterios_estadual_federal_fontereceita_municipal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterios',
            name='deducao_imposto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
