# Generated by Django 5.1 on 2024-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empresa_regime_apuracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vencimento',
            name='mes',
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='dia',
            field=models.DateField(default='2024-01-01'),  # Defina uma data padrão
        ),
    ]
