# Generated by Django 5.1 on 2024-08-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_vencimento_mes_alter_vencimento_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacoes',
            name='data',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='transacoes',
            name='fonte_receita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='dia',
            field=models.DateField(),
        ),
    ]
