# Generated by Django 5.1 on 2024-08-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transacoes_data_transacoes_fonte_receita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='regime_apuracao',
        ),
        migrations.RemoveField(
            model_name='transacoes',
            name='id_empresa_empresa',
        ),
        migrations.AlterField(
            model_name='criterios',
            name='deducao_imposto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='atividade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='responsaveis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estadual',
            name='certificado_digital_estadual',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='federal',
            name='certificado_digital_federal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fontereceita',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='municipal',
            name='certificado_digital_municipal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='transacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tributo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vencimento',
            name='dia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmpresaTransacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_transacoes_transacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transacoes')),
            ],
        ),
    ]
