# Generated by Django 5.1 on 2024-08-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_empresa_regime_apuracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regime_apuracao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
