# Generated by Django 5.1 on 2024-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_empresa_regime_apuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterios',
            name='deducao_imposto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
