# Generated by Django 5.1 on 2024-09-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_criterios_deducao_imposto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('informacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Observacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historico')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaObservacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('id_observacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.observacoes')),
            ],
        ),
    ]
