# Generated by Django 5.1 on 2024-09-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_historico_observacoes_historicoempresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributo',
            name='confirmacao_email',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tributo',
            name='envio_email',
            field=models.DateField(blank=True, null=True),
        ),
    ]
